### ISSUE TITLE
CLI does not produce a valid zip file

### ISSUE THREAD

**Issue by rothgar** [SchumacherFM/wordpress-to-hugo-exporter#1]
Output of php hugo-export-cli.php > export.zip give the following error when trying to unzip export.zip

```
Archive:  export2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of export2.zip or
        export2.zip.zip, and cannot find export2.zip.ZIP, period.
```
using PHP 5.4.20 on wordpress 4.0

I tried with [jekyll exporter](https://github.com/benbalter/wordpress-to-jekyll-exporter) and that worked without issues.

**Comment by smittie** [comment]
On activation in WordPress 4.2.2 I get the following error:

Parse error: syntax error, unexpected T_STRING in /home3/smittiec/public_html/blog/wp-content/plugins/wordpress-to-hugo-exporter-master/hugo-export.php on line 202

Smittie

**Comment by SchumacherFM** [comment]
Please update your PHP version

**Comment by smittie** [comment]
smittiec@smittie.com [~]# php -v
PHP 5.4.40 (cgi-fcgi) (built: Apr 17 2015 17:15:17)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2013, by Zend Technologies

What version is required?

**Comment by SchumacherFM** [comment]
Try for your PHP version instead of `$converter = new Markdownify\ConverterExtra;` use `$converter = new Markdownify\ConverterExtra();`
