### ISSUE TITLE
Means to extract a hosted WP blog?

### ISSUE THREAD

**Issue by bguiz** [SchumacherFM/wordpress-to-hugo-exporter#10]
For a  blog hosted on blah.wordpress.org - so no copy on the local filesystem - how can this utility be used to import to hugo?

**Comment by SchumacherFM** [comment]
THere was once an integration in the WP backend but no idea if it's still working.
A cool tool would to directly import the XML of WP into Hugo

**Comment by bguiz** [comment]
I'd like that!

BTW, I'm not sure if this helps, but some time ago I've written a post about extracting wordpress posts into docpad - but it isn't as thorough as this tool by a long shot. Still, it could be a good reference.

**Comment by bguiz** [comment]
http://blog.bguiz.com/2014/07/10/migrating-from-tumblr-and-wordpress-to-docpad-extraction/

That's the URL of the post I mentioned (but forgot to paste)

**Comment by SchumacherFM** [comment]
Interesting blog post. Thanks! But that XML importer won't happen too soon, despite that can you provide me with some demo xml? Maybe from your blog and some others?
BTW: I once applied at Gen book 8-)

**Comment by hiproz** [comment]
@bguiz  do u want to get others web or u are the owner of  blah.wordpress.org? 
other more: this site can not be  reached now :(

**Comment by SchumacherFM** [comment]
There is hacky work around for a blog hosted on blah.wordpress.org.

Export an XML file from blah.wordpress.org and setup a local worpress on your computer. then import that XML file and you can run this plugin to create the exported files.

use `$ wget -r http://blah.wordpress.org ` to recursively download the wp-content folder ...

**Comment by SchumacherFM** [comment]
One year old issue! Happy birthday! Nothing happend. So it gets closed.
