### ISSUE TITLE
No content exported

### ISSUE THREAD

**Issue by pbolger** [SchumacherFM/wordpress-to-hugo-exporter#11]
Works fine for front matter but I'm getting nothing for the content area. Any ideas?

**Comment by SchumacherFM** [comment]
Nope. Too little information

**Comment by pbolger** [comment]
I'm getting all my posts as md files and each has the appropriate front matter. But below the second set of dashes there's nothing. Like this:

---
title: ICNZ media release – progress update
author: M#### I####
layout: post
date: 2014-05-16
url: /2014/05/icnz-media-release-progress-update/
categories:  - Insurance council of New Zealand
tags:  - Progress Updates
---

**Comment by SchumacherFM** [comment]
Sorry this is pretty hard to debug when I don't have the original data and more information regarding WordPress Version, PHP Version, or MySQL Version.

**Comment by pbolger** [comment]
Yes, sorry. Does it generate any logs?

I'm on the latest WP, 
PHP 5.4.45-0+deb7u1
Server version: 5.5.44-0+deb7u1
That help?

**Comment by SchumacherFM** [comment]
Nope. I should need the original data to debug it and run it directly on my laptop.

**Comment by pbolger** [comment]
I can send you an sql dump if you like. Are you sure you want to do this? Starting to sound like a mission. 
What would the best way to get it to you be?

**Comment by SchumacherFM** [comment]
Share me a dropbox link to my email address: firstname at lastname dot fm

**Comment by hiproz** [comment]
@pbolger give me a whole url of your site : /2014/05/icnz-media-release-progress-update/  , i need check the origin page content .

**Comment by SchumacherFM** [comment]
Closed due to inactivity
