### ISSUE TITLE
Why are posts exported to "_posts" and not "posts"?

### ISSUE THREAD

**Issue by johnmckinzie** [SchumacherFM/wordpress-to-hugo-exporter#12]
I'm looked through the Hugo documentation and cannot find the underscore convention. Why are posts exported to "_posts" and not "posts"?

**Comment by SchumacherFM** [comment]
Good question. No idea. You can send me a PR

**Comment by johnmckinzie** [comment]
Sounds good. I thought I was missing something, but it appears to be the convention for Jekyll. Thanks for the quick response.
