### ISSUE TITLE
new requirements

### ISSUE THREAD

**Issue by hiproz** [SchumacherFM/wordpress-to-hugo-exporter#14]
this is a great tool!
i think it maybe has the below functions : 
1. add the increment export function
2. add the config setting that can list the export history and the date.
3. user can choose total export or increment export.
if user choose increment export ,the tool will export the content from the last export day.

thansks for the work!

**Comment by SchumacherFM** [comment]
Cool! Send me a PR and I'm happy to merge it!

**Comment by hiproz** [comment]
i think the conversion  is fast , so increment  conversion is not so necessary.i will colse this issue.

**Comment by SchumacherFM** [comment]
ok
