### ISSUE TITLE
bug: unicode charactor support issue

### ISSUE THREAD

**Issue by hiproz** [SchumacherFM/wordpress-to-hugo-exporter#15]
i tested the plug in the Chinese env, the title of article that contain the Chinese  will convert not correct

**Comment by SchumacherFM** [comment]
can you fix this? you can send me PR :-)

**Comment by hiproz** [comment]
i have prepare a pr:

1. fix a markdown format display issue: there need an new line before the
--- line
after fix:
[image: 内嵌图片 1]
before:
[image: 内嵌图片 2]
i use the mon markdown editor.

the related code is :
[image: 内嵌图片 3]

2. the unicode url issue ,if the title of the article has chinese,and the
url also has chinese, the file name and url will not be increct,
and can't routed.

i add the urldecode function,i test it im my local mac env ,the english and
chinese title is OK.

pls review the code .

thank you!

2015-12-15 3:15 GMT+08:00 Cyrill Schumacher <notifications@github.com>:

**Comment by SchumacherFM** [comment]
done
