### ISSUE TITLE
the tag format

### ISSUE THREAD

**Issue by hiproz** [SchumacherFM/wordpress-to-hugo-exporter#17]
in the official yaml format of front matter, the tag format  is : 

tags:  ["x", "y"]

but in our export file , the tag is :  

tags: 
  - x
  - y

so ,i think this need to be improved

**Comment by SchumacherFM** [comment]
You are now a Collaborator of this project. You can directly push changes to this repo.
Please be careful and don't f*** things up. I trust you.

Please go ahead with above mentioned fix :-)

**Comment by hiproz** [comment]
for check the spec ：http://www.yaml.org/spec/1.2/spec.html 
i think that it is the hugo's issue:https://github.com/spf13/hugo/issues/1761
:)
