### ISSUE TITLE
Unable to activate due to syntax error

### ISSUE THREAD

**Issue by mjbrender** [SchumacherFM/wordpress-to-hugo-exporter#18]
I added this plugin and it shows up in the plugin list in my admin console: 

<img width="1066" alt="screen shot 2015-12-21 at 9 45 37 am" src="https://cloud.githubusercontent.com/assets/1744971/11933074/9f19c62a-a7c7-11e5-8ad8-fa8e67251c34.png">

When I click Activate, the following error is reported: 

<img width="1103" alt="screen shot 2015-12-21 at 9 46 19 am" src="https://cloud.githubusercontent.com/assets/1744971/11933096/b857193a-a7c7-11e5-8e0d-1c2b17b3eaeb.png">

```
Parse error: syntax error, unexpected T_STRING in /homepages/3/d374491256/htdocs/blog/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php on line 202
```

A few additional notes: 

* on Wordpress version 4.4
* I'm using a hosting provider, so I'm not sure what version of php is installed (I only have sftp access)

If you happen to have recommended troubleshooting steps, let me know. And thank you!

**Comment by mjbrender** [comment]
Note that the line, 202, that it fails on is ` $converter = new Markdownify\ConverterExtra;`

**Comment by SchumacherFM** [comment]
Thanks for reporting. What is your PHP Version?

**Comment by mjbrender** [comment]
@SchumacherFM it's PHP 5.2.

**Comment by SchumacherFM** [comment]
Sorry. Please update PHP to at least 5.4

**Comment by mjbrender** [comment]
That's totally fair :smile: - I just realized I can request an update from my service provider. I'll update and let you know if this resolves the error. Thanks!

**Comment by SchumacherFM** [comment]
Perfect!

at least you won't have such problems with hugo the future ;-)

**Comment by mjbrender** [comment]
hahaha :+1:

**Comment by mjbrender** [comment]
Plugin activated with no problem after updating to 5.6 - thanks again @SchumacherFM! Closing.
