### ISSUE TITLE
No content exported after clicking Tools > Export to Hugo

### ISSUE THREAD

**Issue by mjbrender** [SchumacherFM/wordpress-to-hugo-exporter#19]
I'm past #18 and hit my next snag - I hope others find this helpful too. At the end of a download, I'm left with a file called `hugo-export.zip.download` that's tiny. When I try to unzip it, it turns into a .cpgz, which I then unzip into another .zip. This goes on forever. 

```
-rw-r--r--@   1 myusername  mygroup   3.0K Dec 21 10:35 hugo-export.zip
-rw-r--r--    1 myusername  mygroup   1.6K Dec 21 10:35 hugo-export.zip.cpgz
```

**Comment by mjbrender** [comment]
The problem here was a timeout between my laptop and the wordpress hosting site. I established a better connection (dropped VPN and hardwired in) and downloaded the export folder. 

Sharing this incase others are driven slightly mad by this process :+1:

**Comment by hiproz** [comment]
u can try cli interface command  as the mannual. it is easy also:)

**Comment by SchumacherFM** [comment]
@mjbrender Can you do me favor and export the data from wordpress with its XML file exporter? Only if you wish to share it. You can send me an email to firstname @ lastname dot fm

Reason: with the XML file I can build a golang based converter and even integrate that code directly into hugo.

**Comment by mjbrender** [comment]
Thanks @hiproz - I almost did, but I don't have CLI access on my hosting provider. Just FTP.

@SchumacherFM glad to help. email coming your way and happy to help. I've run ~10 WP sites for a long time and I would like to get better at golang, so I'm converting to Hugo. Plus I'm sick of php :smile:. I'll start with this file.
