### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by JohnBlood** [SchumacherFM/wordpress-to-hugo-exporter#23]
I installed this plugin and used it. It downloaded a zip file, but it would not open. When I tried to unzip with 7zip, it told me that hte file was not correctly setup as a zip file. I used the wordpress to jekyll plugin and converted to hugo.

**Comment by SchumacherFM** [comment]
Can you run it on the command line? Do you have access to it and know how to use it?

It's pretty hard to give you any tips on how to solve your problem because I don't know the whole scope of your server or whatever ....

**Comment by hiproz** [comment]
1）check the size of zip file .
2）run it  on the command line , and use unzip in the linux of /tmp dir 
how to use : 

```
It works just like the plugin, but produces the zipfile at /tmp/wp-hugo.zip:

php hugo-export-cli.php
```

**Comment by SchumacherFM** [comment]
Closed due to inactivity
