### ISSUE TITLE
failing on empty directories

### ISSUE THREAD

**Issue by robsonsobral** [SchumacherFM/wordpress-to-hugo-exporter#24]
Hi!

The loop at line 370, `foreach (glob(trailingslashit($dir) . '*') as $path) {` is failing to run if there are empty directories on `wp-content/uploads/`. I'm sorry, but I don't know how to fix it. I deleted all empty directories and filled the directory of current month with a dummy text file.

Thanks, guys.

**Comment by SchumacherFM** [comment]
Seems like this one has been solved. No one else reported such a problem.

**Comment by weldpua2008** [comment]
Hi,
I have the similar issue when I call site.com/wp-admin/export.php?type=hugo:
```
Warning: Invalid argument supplied for foreach() in /home/site.com/wp-content/plugins/wordpress-to-hugo-exporter-master/hugo-export.php on line 371
PKL7J§≤b?2Ùhugo-export/about/index.mdUë¡N¬@E˜˝äŸ€ö°Ï˙.L\ì–®	jå;@¡D6.˝ì“P©•¥øpﬂyﬂîÿΩôwÔ}gﬁA‡%è… é>ëÀ)(ºﬁSÚ0GÊ9x…ÀàÌQÔ>ˆ˙ΩÑeh;6ËÑAÿΩ √»v£∞{emd≠ÁÃ√7cjÉF¶(P1ujd&sSQ»RVôπé˚7„x2π6¯Bç6i;R’P5CJœ⁄`è3fZ8 j&UÏ.©˙0ÙPõcã\§?]•¯%HÓyW lul√‚ kÜ÷»tùŒ≤wÉY˙e˚ÄL ö∆c)ØƒH/P9£vt-®æÒî^∫Ó˘ìˇ—`wŸÛ5©<≥Ú:
```

**Comment by weldpua2008** [comment]
Fixed line https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/master/hugo-export.php#L371
` foreach ( (array)glob(trailingslashit($dir) . '*') as $path) {`

**Comment by SchumacherFM** [comment]
F*** PHP regarding glob:
> On some systems it is impossible to distinguish between empty match and an error.

@weldpua2008 can you please send me a pull request with your fix?

**Comment by SchumacherFM** [comment]
I'm closing this as too old or maybe even fixed.
