### ISSUE TITLE
Export drops the time of posts

### ISSUE THREAD

**Issue by AndreasOM** [SchumacherFM/wordpress-to-hugo-exporter#25]
With multiple posts on the same date the order gets mixed up.

Changing
    `return date('Y-m-d', $unixTime);`
to
    `return date('c', $unixTime);`
in
    `function _getPostDate [...]`

fixed the issue for me.

Not sure about the other implications, so not creating a pull request.

**Comment by SchumacherFM** [comment]
Interesting. I also have no idea about the side effects. We can add it and see what happens 😎 Just send a PR.

**Comment by AndreasOM** [comment]
PR #26 - only tested this for one of my wordpress to hugo migrations so far,
but "it worked for me".

**Comment by SchumacherFM** [comment]
Thanks a lot. When at least 3 people start complaining we should remove this PR.
