### ISSUE TITLE
Parse error: hugo-export.php on line 202

### ISSUE THREAD

**Issue by routetonull** [SchumacherFM/wordpress-to-hugo-exporter#27]
I can't edit the php.ini file where my website is hosted and I get this error when the plugin is activated with Wordpress:

`Parse error: syntax error, unexpected T_STRING in /web/htdocs/home/wordpress/wp-content/plugins/wordpress-to-hugo/hugo-export.php on line 202`

Are the two things related? Is there a way to fix this other that edit php.ini file?

Thank you.

**Comment by SchumacherFM** [comment]
Which PHP Version are you using?

**Comment by routetonull** [comment]
Hi,
the PHP version is 5.2.17 with this configure command:

`'./configure' '--prefix=/php_5.2.17' '--with-libdir=lib64' '--with-mysql' '--with-mysqli' '--enable-soap' '--with-jpeg-dir=/usr' '--with-zlib-dir=/usr' '--with-png-dir=/usr' '--with-config-file-path=/etc/apache/phpini/php5' '--with-gd' '--with-xpm-dir=/usr' '--enable-gd-jis-conv' '--disable-debug' '--enable-inline-optimization' '--with-kerberos' '--with-imap' '--with-openssl' '--with-imap-ssl' '--with-mcrypt' '--enable-ftp' '--with-xsl' '--with-ttf' '--with-freetype-dir=/usr/include/freetype2/freetype/' '--with-t1lib=/usr/include/' '--with-gettext' '--enable-exif' '--enable-bcmath' '--enable-calendar' '--enable-discard-path' '--disable-path' '--with-bz2' '--with-mhash' '--with-mime-magic' '--with-curl=/curl' '--enable-wddx' '--with-expat' '--disable-ipv6' '--enable-static=mysql' '--enable-static=mysqli' '--with-pdo-mysql' '--enable-fastcgi' '--enable-mbstring' '--without-pdo-sqlite3'`

Streams:

```
Registered PHP Streams	https, ftps, compress.zlib, compress.bzip2, php, file, data, http, ftp

Registered Stream Filters	zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed
```

**Comment by SchumacherFM** [comment]
Sorry. Not Supported. Please upgrade to at least 5.3
