### ISSUE TITLE
Plugin creates corrupt zip

### ISSUE THREAD

**Issue by westermarck** [SchumacherFM/wordpress-to-hugo-exporter#31]
Installed the plugin on a site with Wordpress 4.6.1.

Uploaded the https://github.com/SchumacherFM/wordpress-to-hugo-exporter/commit/14ae4481a88e12f0487ba52f0041bcce836caa76 in Wordpress. Activated and exported. After awhile Chome did start the download of the site.

When trying to extract the ZIP with unzip on Linux the following error message is shown:

```
Archive:  ~/Downloads/hugo-export.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

**Comment by SchumacherFM** [comment]
Seems like your PHP process runs out of time and got terminated. Do you have a chance to run this plugin on the command line?

Or: Can you download a database dump, install it locally on your computer and then run this plugin with your custom PHP settings.

**Comment by westermarck** [comment]
Unfortunatly the Wordpress blog that I tried to export is on a shared host that I don't have shell access to so I cannot try it out in the command line.

I'll do a database dump and install it locally andy try out the plugin later on.

**Comment by SchumacherFM** [comment]
Let me know if this works.

**Comment by tech4him1** [comment]
This exporter is creating a corrupt `.zip` file for me as well.  In 7-zip, the path shows up as `hugo-export.zip//hugo-export/...`.  There is an extra no-name directory as the root directory.

**Comment by SchumacherFM** [comment]
To reproduce it. I need to know: 
- PHP version and its configuration.
- MySQL Version
- Wordpress Version

If you even can find the fix @tech4him1  please send me a pull request. I need a couple of weeks to find time to reproduce it.

**Comment by tech4him1** [comment]
OK, I am looking into this issue a little more and I think mine is separate from this one, so I am going to split it off into a separate bug report.

**Comment by SchumacherFM** [comment]
I'm closing this one as the original reporter doesn't report back and yours is different.
Otherwise. Just open a new issue.
