### ISSUE TITLE
Posts from 2011 and earlier are exported as 0 bytes .md files

### ISSUE THREAD

**Issue by nicolaiarocci** [SchumacherFM/wordpress-to-hugo-exporter#33]
I have a WP blog with posts form 2010 to 2016. Posts from 2012 to 2016 are exported fine, while 2010-2011 are 0 bytes .md files.

**Comment by nicolaiarocci** [comment]
For reference: http://nicolaiarocci.com

**Comment by SchumacherFM** [comment]
Hi Nicolai,

I'm currently unable to fix this but if you send me a pull requests with a fix in it. I'm happy to merge it.

**Comment by nicolaiarocci** [comment]
Eventually a second or third run of the export worked fine. It might be a memory issue? I'm running WP on a small digital ocean instance. Closing the ticket since I somehow solved it.
