### ISSUE TITLE
Windows cannot open zip file correctly.

### ISSUE THREAD

**Issue by tech4him1** [SchumacherFM/wordpress-to-hugo-exporter#34]
* Windows 10
* Wordpress 4.7

In 7-zip, the path shows up as `hugo-export.zip//hugo-export/...`. There is an extra no-name directory as the root directory.

**Comment by tech4him1** [comment]
Related StackOverflow answer (from [CWSpear](http://stackoverflow.com/users/592839/cwspear)):

> When you put a file in the archive, you can't have absolute files (files starting with a slash) or else it won't open in Windows for some reason.
>
> So got it working not because he (Jesse Bunch, the selected answer at the time of this writing) removed the containing folder but because he removed the starting slash.
>
> I fixed the issue by changing
>
> $zip->addFile($file, $file); // $file is something like /path/to/file.png
> to
>
> // we make file relative by removing beginning slash so it will open in Windows
> $zip->addFile($file, ltrim($file, '/'));
> and then it was able to open in Windows!
http://stackoverflow.com/a/11350197

So we should just be able to remove the beginning slash from [`$local_path`](https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/625125e03feb134e4ba484d2dd279659db3810e6/hugo-export.php#L385) for the filename in the zip file.  I can test it on Windows and Ubuntu if you want.

**Comment by SchumacherFM** [comment]
Done! Please download the new source and test it!

**Comment by tech4him1** [comment]
Works on Windows 10
