### ISSUE TITLE
Exporter stripping iframes.

### ISSUE THREAD

**Issue by tech4him1** [SchumacherFM/wordpress-to-hugo-exporter#36]
Any `iframe`s in a post or page are being stripped out when exported.  Other HTML is left in, so shouldn't `iframe`s be left in as well?  This could possibly be a Wordpress or Markdownify issue as well.

**Comment by SchumacherFM** [comment]
Ok. What should we do?

**Comment by tech4him1** [comment]
I'll see if I can figure it out when I get a chance, I just thought I would make an issue to document it and see if you had any ideas right away.

**Comment by tech4him1** [comment]
Do you mind how many issues/PRs I have been making?

**Comment by SchumacherFM** [comment]
It's great when you open an issue or a PR. But especialy for issue you must communicate exactly what the problem is, the unexpected result and the expected result. Finally maybe how you wish to have fix it or how you would like to fix it with the next pull request.

**Comment by tech4him1** [comment]
Will do, sorry that this one was unclear.

**Comment by tech4him1** [comment]
It looks like Markdownify is the one removing tags ([Converter.php#L140](https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/19baf765bd27d76cc87c7e7b59325bfec0d60cd0/includes/markdownify/Converter.php#L140) and [Converter.php#L305](https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/19baf765bd27d76cc87c7e7b59325bfec0d60cd0/includes/markdownify/Converter.php#L305)):
```php
/**
 * html tags to be dropped (contents will not be parsed!)
 *
 * @var array<string>
 */
protected $drop = array(
    'script',
    'head',
    'style',
    'form',
    'area',
    'object',
    'param',
    'iframe',
);
```
```php
protected function parse()
{
    $this->output = '';
    // drop tags
    $this->parser->html = preg_replace('#<(' . implode('|', $this->drop) . ')[^>]*>.*</\\1>#sU', '', $this->parser->html);
```

**Comment by SchumacherFM** [comment]
I don't know the disallowed tags in Wordpress. Is there an official list?
Otherwise. If you need for yourself iframes in the markdown then just edit the `Converter.php` file on your own server and comment out the `iframe` entry and re-run the export.

Assuming that everybody would like to keep iframes ... is a bit vague, as you are the first one who needs them ;-)

**Comment by tech4him1** [comment]
> I don't know the disallowed tags in Wordpress. Is there an official list?
I thought the `$allowedposttags` list in `wp_kses` was it, but it dosen't include `iframe`s and they still work, so I guess I really don't understand Wordpress' filtering.  We can just close this for right now.

> Assuming that everybody would like to keep iframes ... is a bit vague, as you are the first one who needs them ;-)
Well, yes, obviously 😄.  Thanks for your patience with my ambiguous issue.
