### ISSUE TITLE
Export fails if wp-content/uploads folder is missing

### ISSUE THREAD

**Issue by richardtallent** [SchumacherFM/wordpress-to-hugo-exporter#38]
For some reason or another, I didn't have an uploads folder. I don't recall if I deleted it for non-use or if WordPress only creates it when it is used the first time. Either way, the exporter bailed. I created an empty folder and the export appears to have run properly now.

**Comment by SchumacherFM** [comment]
Seems like solved and >2 years old, so I'm closing this issue.
