### ISSUE TITLE
Plugin activation fails on Wordpress 4.7.3

### ISSUE THREAD

**Issue by dchucks** [SchumacherFM/wordpress-to-hugo-exporter#39]
When I try to activate the plugin I get the error, "Plugin could not be activated because it triggered a fatal error.", details of the error:
`Parse error: syntax error, unexpected T_STRING in <root>/wp-content/plugins/wordpress-to-hugo-exporter-master/hugo-export.php on line 202`

**Comment by SchumacherFM** [comment]
Please update your PHP version ;-)

**Comment by dchucks** [comment]
Agree there, I realised this later and commenting out appropriate code (like Namspace or the static reference static::) worked and I was even able to download the zip :)  Thanks for this excellent tool.
