### ISSUE TITLE
Call to a member function find() on boolean

### ISSUE THREAD

**Issue by hilja** [SchumacherFM/wordpress-to-hugo-exporter#43]
When using the CLI `php hugo-export-cli.php` I'm get this error:

```
PHP Fatal error:  Uncaught Error: Call to a member function find() on boolean in 
/ ... /content/themes/cm/functions/dom-manipulaion.php:41
```

WP is installed as a submodule, my dir structure:

```
├── content
│   ├── plugins
│   ├── themes
│   └──uploads -> ../shared/content/uploads
└── wp
    ├── wp-admin
    ├── wp-content
    └── wp-includes
```

I had to update the two include path in `hugo-export-cli.php` because WordPress is in `./wp`. Could this have something to do with it?

I'm running PHP 7.0.19 and WordPress 4.7.5.

**Comment by hilja** [comment]
When running it with wp-cli `wp hugo-export > export.zip` I get a different error:

```
PHP Fatal error:  Uncaught Error: Call to a member function export() on null in / ... 
 /content/plugins/wordpress-to-hugo-exporter-1.5.0/hugo-export.php:579
```

This guy here https://github.com/SchumacherFM/wordpress-to-hugo-exporter/issues/29 had the same issue, I installed `php7.0-mbstring` package but it doesn't seem to help. I did restart PHP after the install.

**Comment by SchumacherFM** [comment]
Hi. Sorry for the delay (holidays). I can't really help ... but have you verified that mbstring shows up in the phpinfo() output?

**Comment by hilja** [comment]
Yes it does show there.

Thanks for the hard work maintaining this.

**Comment by hilja** [comment]
Related side note: I was looking into other static site generators, and Hexo, for example, does the exporting using the WP native XML exporter and then has small node script to parse XML to JS and populate the templates. This is obviously a totally different approach, but to me it was way easier to do, I didn't have to install or download anything in my server.

**Comment by SchumacherFM** [comment]
Yes there is an idea to use the native WP XML to import it into Hugo. But no one has at least the time or is in the mood to implement that into Hugo.
Have a look here https://github.com/spf13/hugo/issues/100

**Comment by SchumacherFM** [comment]
Seems like solved and >2 years old, so I'm closing this issue.
