### ISSUE TITLE
can't activate plugin

### ISSUE THREAD

**Issue by agahov** [SchumacherFM/wordpress-to-hugo-exporter#47]
Hello, 
I uploaded this plugin to wp, but cant activate it on the dashboard.
i got thls error:

Parse error: syntax error, unexpected T_STRING in /home/u89339/orangefrog.ru/www/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php on line 221

thank for any ideas,
Alexandr Gakhov

**Comment by SchumacherFM** [comment]
Please update your PHP version. It is too old.
