### ISSUE TITLE
Memory Exhausted While Exporting BLog

### ISSUE THREAD

**Issue by noelob** [SchumacherFM/wordpress-to-hugo-exporter#48]
While exporting a large WordPress blog, I get the following error:
`PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 1512064064 bytes) in /var/www/blogs/blog_com/blog/wp-content/plugins/wordpress-to-hugo-exporter-1.5.0/includes/markdownify/Converter.php on line 793`

I've bumped the memory up to 4G by adding a line to hugo-export-cli.php:
`ini_set('memory_limit', '4096M');`
but still it fails before completion. Is this a direct result of the size of the blog? Is there another way to export without continually increasing the memory of the process?

**Comment by SchumacherFM** [comment]
Hi,

you can also set the mem limit to `ini_set('memory_limit', -1);` which indicates use all memory. If it still breaks ... no idea how to solve this with such a huge blog :-(

**Comment by noelob** [comment]
Thanks for the suggestion. I'm running this on a production server so setting it to use all the memory is not something I'm will to do :(

**Comment by SchumacherFM** [comment]
The only thing I can then suggest is, that you dump the blog into a SQL or whatevery file, download it on your local machine and then run the exporter there.

**Comment by noelob** [comment]
Thanks, sounds like the next logical thing to try.

**Comment by SchumacherFM** [comment]
Seems like solved and ~2 years old, so I'm closing this issue.
