### ISSUE TITLE
img src tag corruption with double-byte characters in alt

### ISSUE THREAD

**Issue by rippler** [SchumacherFM/wordpress-to-hugo-exporter#5]
I executed Exporter from Tools and value of my `src` tag (in `img`) ended up corrupt (`base64...`), see https://github.com/spf13/hugo/issues/1170.
Post content and other `img` tags (e.g. `dst-src`) did not get corrupt.

**Comment by SchumacherFM** [comment]
No idea where this gets corrupted. Maybe somehwere in the Markdownify class.
If you can send me a PR with a new Markdownify class which fixes it. I'm happy to merge it.
