### ISSUE TITLE
high utf8 in title breaks things

### ISSUE THREAD

**Issue by guycalledseven** [SchumacherFM/wordpress-to-hugo-exporter#50]
I played with exporter the other night and noticed it did not play well with high utf characters.

I had issues with non printable chars (e.g. `&#13;`), double quotes (`&#34;`), single quotes (`&#39;` and `&apos;`).. in my titles, causing invalid .md files generation, breaking hugo, looking bad (all titles on site contained codes, not characters) etc.

Eg, one blog post had title with – in it (`&#8211;`). Front matter looked like this:

```
title: 'Top Gear 03×13 &#8211; BBC camera and editing crew are gods'
author: Daemon
type: post
date: 2009-07-06T08:35:56+00:00
url: /2009/07/06/top-gear-03x13-bbc-camera-and-editing-crew-are-gods/
views:
  - 129
categories:
  - developers journal
```

This one was causing hugo to break with __yaml: invalid trailing UTF-8 octet__
```
Started building sites ...
ERROR 2017/11/10 00:00:59 failed to parse page metadata for "posts/2009-07-06-top-gear-03x13-bbc-camera-and-editing-crew-are-gods.md": yaml: invalid trailing UTF-8 octet
Error: Error building site: Errors reading pages: Error: failed to parse page metadata for "posts/2009-07-06-top-gear-03x13-bbc-camera-and-editing-crew-are-gods.md": yaml: invalid trailing UTF-8 octet for 2009-07-06-top-gear-03x13-bbc-camera-and-editing-crew-are-gods.md
```

Other high ut8 chars just looked like codes in titles in generated code.

I created [PR](https://github.com/SchumacherFM/wordpress-to-hugo-exporter/pull/49) #49 

Thanks for great work!
Best!

**Comment by SchumacherFM** [comment]
👏👏👏

Merged! Thank you very much!

**Comment by guycalledseven** [comment]
👍
