### ISSUE TITLE
How to run this on wordpress.com or exported xml files?

### ISSUE THREAD

**Issue by fatih** [SchumacherFM/wordpress-to-hugo-exporter#51]
Hi,

Can you please describe how we can run this on an exported xml file from wordpress.com? There is no way to install the plugin to wordpress.com so I'm curious how to achieve it. Thanks

**Comment by SchumacherFM** [comment]
Good morning,
The script does a DB connection and reads the data from the SQL tables and can't work on a XML file.
The only solution is to import the XML file into your local wordpress installation and then install there the plugin and run the conversion. Hope that helps.

**Comment by fatih** [comment]
Thanks @SchumacherFM 

I thing adding this to the README for wordpress.com users would be valuable as those people don't have access to the DB. In my case I wasn't sure I could do it on a locally running wordpress with importing the XML file from my wordpress.com blog. Thanks

**Comment by SchumacherFM** [comment]
Done! Maybe you can prove-read it.

**Comment by fatih** [comment]
Nice! thanks a lot, it looks good!
