### ISSUE TITLE
Call to member function export() on null

### ISSUE THREAD

**Issue by AntJanus** [SchumacherFM/wordpress-to-hugo-exporter#52]
Got this error when trying to run `wp hugo-export`

```
PHP Fatal error:  Uncaught Error: Call to a member function export() on null in /var/www/site/wp-content/plugins/wordpress-to-hugo-exporter-master/hugo-export.php:583
```

Here's my setup:

```
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.22-0ubuntu0.16.04.1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/site
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.4.1
```

**Comment by SchumacherFM** [comment]
Seems like that `$je` on line https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/master/hugo-export.php#L583 didn't get instantiated in https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/master/hugo-export.php#L572

No idea, maybe there is somewhere a previous error or incorrect PHP ini setting which doesn't allow global variables ...

**Comment by dermatz** [comment]
same here...

`wp hugo-export > export.zip --allow-root
PHP Fatal error:  Uncaught Error: Call to a member function export() on null in /var/www/vhosts/xxx/httpdocs/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php:582
Stack trace:
#0 [internal function]: Hugo_Export_Command->__invoke(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(353): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(376): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1102): WP_CLI\Runner->_run_command_and_exit()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/bootstrap.php(75):  in /var/www/vhosts/xxx/httpdocs/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php on line 582
Fatal error: Uncaught Error: Call to a member function export() on null in /var/www/vhosts/xxx/httpdocs/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php:582
Stack trace:
#0 [internal function]: Hugo_Export_Command->__invoke(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(353): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(376): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1102): WP_CLI\Runner->_run_command_and_exit()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/bootstrap.php(75):  in /var/www/vhosts/xxx/httpdocs/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php on line 582``

**Comment by AntJanus** [comment]
Ah, i wish I remembered to go back to this. I got everything to successfully run. I think it might have been a missing extension or some setting in php.ini? I'm not sure.

**Comment by dermatz** [comment]
Ok, i will try it on local environment

**Comment by SchumacherFM** [comment]
Maybe, just an idea: `global/s` are disabled in the php.ini file or somewhere else or any other security setting ...

**Comment by chmac** [comment]
FYI, I hit the same error and was able to bypass it by using the php command line option instead like:

    php hugo-export-cli.php

**Comment by SchumacherFM** [comment]
Thanks for the update!

**Comment by amca01** [comment]
The solution is to add `global $je;` in `hugo-export.php` just before the line `$je = new Hugo_Export();`.  For some reason php seems to have difficulty with global variables.
