### ISSUE TITLE
Youtube Video Links are not included in the exported markdown file

### ISSUE THREAD

**Issue by hydrogen2oxygen** [SchumacherFM/wordpress-to-hugo-exporter#53]
If a link to youtube exist in post (just the plain url) it will not be exported.

**Comment by SchumacherFM** [comment]
Can you debug it please and send a Pull Request to fix it?

**Comment by hydrogen2oxygen** [comment]
Hi, yes I will fix it on my test installation and then send a pull request.

**Comment by SchumacherFM** [comment]
Seems like solved and ~1 year old, so I'm closing this issue.
