### ISSUE TITLE
Request Timeout 500

### ISSUE THREAD

**Issue by yudyananda** [SchumacherFM/wordpress-to-hugo-exporter#55]
Hi I just installed this plugin, then click export to hugo, nothing happend for a while it was just loading then finally throw me to request timeout.

The blog have about 200 post, any clue?

thanks

**Comment by hydrogen2oxygen** [comment]
Hi, inside the php.ini set a higher value to
max_execution_time=300

then restart the Apache server.

**Comment by yudyananda** [comment]
thank you its working now until the download part. I cannot download the file, its always failed

I'm using XAMPP on Windows, I wonder if you can show me exactly where is the file hugo-export.zip stored

**Comment by hydrogen2oxygen** [comment]
Well then try to download the wordpress export and import it into a local apache server, like XAMPP, and download the hugo export from there. I did it the same way with my blog of over 900 posts.

**Comment by yudyananda** [comment]
If someone have experience like me
- wordpress on local windows
- use xampp
- always failed when download hugo-export.zip

check `'C:\Users\%USERNEAME%\AppData\Local\Temp/wp-hugo-xxxxxxx` you will find wp hugo folder in there complete with your hugo content.
