### ISSUE TITLE
Exported .zip file turns into a .cpgz file when I click on it. Never ending loop.

### ISSUE THREAD

**Issue by mbbender** [SchumacherFM/wordpress-to-hugo-exporter#56]
When I run the exporter it creates a huge-export.zip file. When I click on that (latest version of mac os) it creates a hugo-export.zip.cpgz file which if I click on creates another hugo-export.zip file... in a never ending fashion. Looked into using ditto but it says it can't identify the format.

Are there any exprot logs produced somewhere maybe I can review to see if there was an issue with the export?

**Comment by mbbender** [comment]
Seems to have been an out of memory issue. Worked using it CLI style. Maybe would just be good if it bombed out instead of giving a file that looks like it worked.

**Comment by SchumacherFM** [comment]
You are the first one who has this kind of error ;-)

Ok, please close this issue if all is fine.

**Comment by mbbender** [comment]
You want me to close it? I guess I assumed if the user hit the php memory allocation limit they would hit this also? I don't mind closing it, but I do think it's an issue in that it appeared the export worked, but when attempting to use the file it was corrupt. It was also consistent I downloaded it 3 times with the same results using the WP admin interface.

**Comment by yudyananda** [comment]
@mbbender I have the same issue

**Comment by WANG-lp** [comment]
@mbbender You may need to try a different unzip tool rather than the mac os native one. The integrated with the Finder app has some issue with some zipped files.

**Comment by muellermartin** [comment]
I also have the same issue and tried `unzip` on the command line, but it also appears to have problems with the ZIP file as shown in the error message:

```
Archive:  hugo-export.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of hugo-export.zip or
        hugo-export.zip.zip, and cannot find hugo-export.zip.ZIP, period.
```

I also tried increasing the PHP (version 5.6.36) memory limit by setting `memory_limit` to `1024M`, but that also didn't help.

**Comment by githubvinod** [comment]
I have the same issue but tried with Linux to extract the zip folder.It worked

**Comment by SchumacherFM** [comment]
Seems like solved and ~1 year old, so I'm closing this issue.
