### ISSUE TITLE
Exported site not buildable?

### ISSUE THREAD

**Issue by CyberShadow** [SchumacherFM/wordpress-to-hugo-exporter#58]
Hi, and thank you for this tool!

I'm trying to migrate my blog away from Wordpress. I've successfully exported the ZIP file, however, the resulting site doesn't seem to be close to buildable.

Out of the box, running `hugo` in the unzipped `hugo-export` directory, results in:

```
ERROR 2018/03/02 05:36:15 No 'baseURL' set in configuration or as a flag. Features like page menus will not work without one.
Total in 6 ms
Error: Error building site: No source directory found, expecting to find it at /home/vladimir/work/blog/hugo-export/content
```

Fixing the immediate errors (changing `url` to `baseURL` in `config.yaml`, and creating the `content` directory) causes `hugo` to execute successfully, but it still does not generate any HTML files - only some XML files containing blank ATOM feeds. None of the exported blog posts seem to have been picked up.

Are there any additional steps that one must do after the export?

I noticed that when following the instructions for creating a new site on https://gohugo.io/getting-started/quick-start/ , the resulting directory structure is quite different from that generated by this exporter. For example, the exported ZIP file has `about`, `index`, `posts`, `topics` and `wp-content` directories, whereas the new Hugo site template has `archetypes`, `content`, `data`, `layouts`, `static`, and `themes` directories, and none of those are present in the other. The configuration file is also `.toml` instead of `.yaml` - it's as if the two are for different tools entirely.

Perhaps something changed in a breaking way in `hugo` itself?

Edit: Well, I figured it out - the missing step was to move all the files, except the configuration, to an existing Hugo site skeleton's `content` directory. I'll leave this open as it seems there are some actionable points mentioned above, but feel free to close at your discretion. Thanks!

**Comment by SchumacherFM** [comment]
Thanks for reporting and awesome that you figured it out by yourself!

Regarding the folder structure, no one cares as the migration is a one off and you move the files manually into the content folder. So I'm closing this issue.
