### ISSUE TITLE
Export custom post type?

### ISSUE THREAD

**Issue by christopherisnow** [SchumacherFM/wordpress-to-hugo-exporter#59]
I'm trying to export a WP site with the Portfolio Press theme: https://wptheming.com/portfolio-press/. Most of my content is saved as the custom post type "portfolio". 

The export process does not output any portfolio posts. How do I include this custom post type?

**Comment by hydrogen2oxygen** [comment]
This looks like a extra feature from the plugin "Portfolio Press", which does save the portfolio data not as regular posts or pages. Therefore it would require to develop a new function in the exporter.

**Comment by funkydan2** [comment]
@christopherisnow have you had a go at expanding the plugin to deal with your custom posts? I'm thinking of doing the same for [Wordpress Sermon Manager](https://wpforchurch.com/wordpress-plugins/sermon-manager/) and would love to look at your code if you've been successful.

**Comment by christopherisnow** [comment]
I did have success, but with the `exitwp` [https://github.com/thomasf/exitwp/issues/72#issuecomment-376973210](plugin:https://github.com/thomasf/exitwp/issues/72#issuecomment-376973210)

**Comment by SchumacherFM** [comment]
Seems like solved and ~1 year old, so I'm closing this issue.
