### ISSUE TITLE
wp-content is not exported

### ISSUE THREAD

**Issue by tanzaho** [SchumacherFM/wordpress-to-hugo-exporter#6]
Hi Cyrill,

Do you think that we could add an export of local files (ie. `wp-content' ) so that images and other files can go to the static folder ?

**Comment by SchumacherFM** [comment]
Of course! Send me a PR :-)

**Comment by michaelsync** [comment]
@tanzaho it would be interesting.. but will it create more time-out error like this https://github.com/SchumacherFM/wordpress-to-hugo-exporter/issues/8 ?

**Comment by hiproz** [comment]
for this scenario , i think it is not a good idea:
1. for the operation from wordpress page plugin ,it will increase the zip file ,it will so big  and cost more time to export from server to local
2. for the ssh user.it will be a scp cmd that not spend so many time 

most people export  from page .so i think not include the wp-content is better.

**Comment by SchumacherFM** [comment]
all good arguments especially from @hiproz 

`wget -r http://mydomain.com` would be useful to download all content when there is no FTP or SSH access.

**Comment by SchumacherFM** [comment]
Closed due to inactivity
