### ISSUE TITLE
Call to member function export() on null: solution

### ISSUE THREAD

**Issue by amca01** [SchumacherFM/wordpress-to-hugo-exporter#60]
This issue was closed, but in fact the solution is to include the line

    global $je;

in the file `hugo-export.php` just before the line `$je = new Hugo_Export();`.  For some reason php (or at least version 5.6) seems to have trouble with global variables.

**Comment by SchumacherFM** [comment]
Can you please send a pull request, which I can merge? Thanks!

**Comment by SchumacherFM** [comment]
Seems like solved and ~1 year old, so I'm closing this issue.
