### ISSUE TITLE
White Screen?

### ISSUE THREAD

**Issue by funkydan2** [SchumacherFM/wordpress-to-hugo-exporter#63]
Hi,

I've just installed the 1.8 release to my Wordpress 4.9.6 site. Once the plugin is installed, the 'Export to Hugo' entry shows up in the *Tools* menu. However, clicking on the menu item just leads to a white screen.

I've checked the settings for php 7.0, and it looks like the zip module is loaded.

Any tips on how to debug this?

**Comment by funkydan2** [comment]
The only thing I can see is an error in the php log
```
Unsupported ErrorDocument URL: default, must start with '/' or 'http'.
```

**Comment by jnoxon** [comment]
I ran into this on WordPress 5.0.2. Additionally, when running hugo-export-cli.php directly, I get this:

```PHP Fatal error:  Cannot redeclare Markdownify\Converter::handleTag_iframe() in /var/www/wpsite/htdocs/wp-content/plugins/wordpress-to-hugo-exporter-1.8.0/includes/markdownify/Converter.php on line 925```

**Comment by SchumacherFM** [comment]
Seems like solved and ~1 year old, so I'm closing this issue.
