### ISSUE TITLE
export doesn't include proper directory structure

### ISSUE THREAD

**Issue by dalenoe** [SchumacherFM/wordpress-to-hugo-exporter#64]
does this need to be updated for newer versions of hugo?

**Comment by SchumacherFM** [comment]
I don't know what you mean. Examples?

**Comment by dalenoe** [comment]
There are missing directories. I will update the ticket later with the actual directories that were missing..

**Comment by Meligy** [comment]
I think I'm facing the same issue.

The directory generated by the tool includes sub-directories for each of the blog categories, and a `config.yaml` file.

But the Hugo site folder for a new created site contain:

```
archetypes, config.toml, content, data, layouts, resources, static, themes
```

It looks like the posts should go into the `content` folder with some structure, but I'm not sure. Only playing with Hugo for the first time.

**Comment by SchumacherFM** [comment]
closing due to age
