### ISSUE TITLE
Configure Export Path Format

### ISSUE THREAD

**Issue by Doocey** [SchumacherFM/wordpress-to-hugo-exporter#65]
Hi there,

Great job on this plugin, it works very well for most cases, and I have used it successfully in previous builds.

However, I am hoping you may be able to shed some light on the way the exported .md files for posts are processed. 
I have a normal WordPress permalink structure of /year/month/day and as per usual, the markdown frontmatter includes that, as desired. 

The individual .md files are prefixed with the following format: **Y-m-d-** (as noted in the attached screenshot PHP date() function)

<img width="1158" alt="current-format" src="https://user-images.githubusercontent.com/8182932/43542148-3f965d1c-959a-11e8-83fd-281f716aa651.png">

My question is whether I can the export format so that posts are placed in subdirectories like so:

<img width="271" alt="desired-format" src="https://user-images.githubusercontent.com/8182932/43542289-967158f8-959a-11e8-8df9-b92f3e24fe5b.png">

So ultimately, upon creation of the the .md files for posts, they are placed in a nested folder format of year/month/day/file-name.md. 
I have tried doing so by editing the plugin, editing date format to **YY"/"mm"/"dd** and running an export locally, but it baulks at exporting the posts.

I am trying to pull these .md files in using GatsbyJS, and while I can rename & place the individual files into the subfolder structure, I have over 300 entries which I'd prefer to avoid editing by hand!

I thought my new format is along the right track, but I shall see whether you have an advisable play in this situation before moving on.

Thank you!

**Comment by SchumacherFM** [comment]
closing due to age. reopen if desired.
