### ISSUE TITLE
Error exporting

### ISSUE THREAD

**Issue by igr** [SchumacherFM/wordpress-to-hugo-exporter#66]
Cannot redeclare Markdownify\Converter::handleTag_iframe() in /home/oblac203/public_html/wp-content/plugins/wordpress-to-hugo-exporter-1.8.0/includes/markdownify/Converter.php on line 925

**Comment by SchumacherFM** [comment]
Seems like you loaded `Markdownify\Converter` twice. I've never seen this error before.

**Comment by igr** [comment]
I really don't know that - I just have few plugins installed and that's it. Do you think that some of the plugins may be responsible for this?

**Comment by igr** [comment]
Just exported to Jekyll (via linked plugin on the readme) - and it worked.

**Comment by jamielaundon** [comment]
Hello,

I've replicated this when using [release v 1.8.0](https://github.com/SchumacherFM/wordpress-to-hugo-exporter/releases/tag/v1.8.0) which has two instances of handleTag_iframe() in Markdownify\Converter.
Resolved by cloning the latest version instead.

**Comment by ryanmr-daugherty** [comment]
Thanks @jamielaundon, I had pulled the release 1.8.0 also, and it failed with the same error. The current master still works fine. Hopefully a new release is made soon so others can skip the broken build.
