### ISSUE TITLE
Export doesn't html-decode &rsquo;

### ISSUE THREAD

**Issue by MayeulC** [SchumacherFM/wordpress-to-hugo-exporter#67]
Hi,

I have a wordpress website that has a lot of `&rsquo;` (that's `’`, an apostrophe) in its titles and content. The `&rsquo;` appears verbatim in the hugo website, which isn't nice.

This tool should probably decode any html-encoded special character, or use a whitelist.

Special care has to be made for the above character: I batch-converted it to the single-quote 'prime' character using `sed`, but it turned out this was a problem in the single-quoted page titles; although thinking about it a bit more, I should just have used the unicode char  `’`.

Thanks a lot for the tool!

**Comment by SchumacherFM** [comment]
closing due to age. reopen if desired.
