### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by stncrn** [SchumacherFM/wordpress-to-hugo-exporter#68]
On a Wordpress 4.9.8 install, with both the 1.8.0 release and the master branch of your plugin, 

When using the plugin through the admin panel, I am getting a blank page.

When using it through PHP CLI, I get : 
`PHP Fatal error:  Cannot redeclare get_file_description() (previously declared in /var/www/_website/_path/wp-admin/includes/file.php:78) in /var/www/_website/_path/wp-admin/includes/file.php on line 94
`

**Comment by juliandkatz** [comment]
I'm getting this as well.  Running one of the wordpress bitnami AMIs in AWS.

```
bitnami@ip-172-26-7-176:~/apps/wordpress/htdocs/wp-content/plugins/wordpress-to-hugo-exporter-master$ php hugo-export-cli.php
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bitnami/php/lib/php/extensions/zip.so' - /opt/bitnami/php/lib/php/extensions/zip.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Fatal error:  Cannot redeclare get_file_description() (previously declared in /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/file.php:78) in /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/file.php on line 94
```

**Comment by David-Else** [comment]
I just tried to use it via the admin and got a blank page with WP 5.02, PHP 7.1.

I have no access to my php.ini file, so I don't know if that is involved. tools -> export to hugo:

`mysite/wp-admin/export.php?type=hugo` is displayed on the top and screen is blank.

**Comment by svennd** [comment]
Similar : 
`Fatal error: Cannot redeclare Markdownify\Converter::handleTag_iframe() in /wp-content/plugins/wordpress-to-hugo-exporter-1.8.0/includes/markdownify/Converter.php on line 925`
