### ISSUE TITLE
Fatal error: Uncaught Error: Class ‘ZipArchive’ not found.

### ISSUE THREAD

**Issue by csereno** [SchumacherFM/wordpress-to-hugo-exporter#69]
I received this error when using the plugin on a self-hosted WordPress installation. I then tried the cli form and received an error there as well. I believe it can’t find zip.so as it doesn’t exist on my server. Is this something I should add or is there a workaround? Thanks!

`Fatal error: Uncaught Error: Class 'ZipArchive' not found in /var/www/html/wp-content/plugins/wordpress-to-hugo-exporter-master/hugo-export.php:406 Stack trace: #0 /var/www/html/wp-content/plugins/wordpress-to-hugo-exporter-master/hugo-export.php(335): Hugo_Export->zip() #1 /var/www/html/wp-content/plugins/wordpress-to-hugo-exporter-master/hugo-export.php(81): Hugo_Export->export() #2 /var/www/html/wp-includes/class-wp-hook.php(286): Hugo_Export->callback(Object(WP_Screen)) #3 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /var/www/html/wp-admin/includes/class-wp-screen.php(376): do_action('current_screen', Object(WP_Screen)) #6 /var/www/html/wp-admin/includes/screen.php(232): WP_Screen->set_current_screen() #7 /var/www/html/wp-admin/admin.php(189): set_current_screen() #8 /var/www/html/wp-admin/export.php(10): require_once('/var/www/html/w...') #9 {main} thrown in /var/www/html/wp-content/plugins/wordpress-to-hugo-exporter-master/hugo-export.php on line 406`

**Comment by csereno** [comment]
I installed php-zip (sudo yum install php-zip). It still failed for some reason through the GUI, but the cli method did generate a zip file. I will look at the files inside the zip tomorrow to see if it was actually successful. I may have resolved my issue though.

**Comment by aarmora** [comment]
@csereno This helped me.

Thanks!
