### ISSUE TITLE
Discuss about markdownify lib

### ISSUE THREAD

**Issue by eercanayar** [SchumacherFM/wordpress-to-hugo-exporter#71]
Hey everyone,

How is your results about markdown format of your wordpress posts? Mine is just "ok" since html is also supported in hugo. But markdownify library is performing very bad. I see that it couldn't convert even so basic <img or <a tags. Manual edit is needed almost every post. Any contributor working on this? Or maybe I can have a look for a way to better markdownifying and create a PR for this.

**Comment by SchumacherFM** [comment]
Hey there, if the PR loos reasonable and the plugin works as expected I'm gonna merge it.

**Comment by SchumacherFM** [comment]
closing due to age. reopen if desired. we've updated the markdownify lib ;-)
