### ISSUE TITLE
Error with Facebook share

### ISSUE THREAD

**Issue by lipaonline** [SchumacherFM/wordpress-to-hugo-exporter#72]
Hello this website looks using your plugin 👍 http://www.ravelrumba.com/blog/json-google-spreadsheets/
I know this, because when i share it Facebook, i get an error
http://www.ravelrumba.com/blog/json-google-spreadsheets/?fbclid=IwAR2g80sNVsOnaMSNMz09tUXGWpBkwYHzSZp5HwOkUuhfi8_C6sjNI9hHewE

Parse error: syntax error, unexpected T_STRING in /home/farnaby/webapps/ravelrumba_wp/wp/wp-content/plugins/wordpress-to-hugo-exporter-master/hugo-export.php on line 202

**Comment by SchumacherFM** [comment]
Hi, sorry I don't have an idea. If I look up whats on line 202, I see a break statement: https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/master/hugo-export.php#L202

**Comment by SchumacherFM** [comment]
closing due to age. reopen if desired.
