### ISSUE TITLE
Exported zip file is unrecognized - cannot be opened

### ISSUE THREAD

**Issue by i-bsd** [SchumacherFM/wordpress-to-hugo-exporter#73]
Entire process seems to work fine but the ZIP file it produces cannot be read or extracted from (FreeBSD).

Anyone else having this issue?

**Comment by i-bsd** [comment]
Just ran the CLI version and got a bunch of output like this (removed username and hostname):

PHP Warning:  ZipArchive::close(): Invalid or uninitialized Zip
object in /home/-----/-----.com/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php on line 412

**Comment by SchumacherFM** [comment]
closing due to age. reopen if desired.

**Comment by amirHHP** [comment]
Hi. I have some problem like this. I get a zip with zero bytes and can't open it. 
[hugo-export (2).zip](https://github.com/SchumacherFM/wordpress-to-hugo-exporter/files/10330028/hugo-export.2.zip)

**Comment by SchumacherFM** [comment]
If it is zero I assume that PHP can't read the files and folders and so adds nothing to the zip file.

**Comment by amirHHP** [comment]
OK, what is the solution? I active the zip module and added extension=zip.so to php.ini.
I also searched for this problem and didn't find anything.
