### ISSUE TITLE
CLI: Should exit if the configured temp folder is invalid

### ISSUE THREAD

**Issue by lanshunfang** [SchumacherFM/wordpress-to-hugo-exporter#76]
When I call 
```php
php hugo-export-cli.php ~/data/hugo/tmp/ 
```
I forgot to create `~/data/hugo/tmp/` folder and the script still proceeded with default `/tmp` folder without any warning. I spent a while to debug the PHP file as a result of that. It would be helpful if we could notify user that the tmp folder passed in is invalid.

BTW, we may want to document it down the way of changing `tmp` folder path in cli. For a gigantic WordPress website like us, OS `/tmp` doesn't have sufficient space to do the job (for our case, `~/data` mounts another AWS drive)

Thanks.

**Comment by lanshunfang** [comment]
Here are the changes if you want ( I am not a collaborator):

```php
<?php
/*
 * Run the exporter from the command line and spit the zipfile to STDOUT.
 *
 * Usage:
 *
 *     $ php hugo-export-cli.php > my-hugo-files.zip
 * 
 * Usage: (With configured tmp folder if the avaiable space in system /tmp is insufficent for migration)
 * 
 *     $ php hugo-export-cli.php /mnt/tmp-folder
 *
 * Must be run in the wordpress-to-hugo-exporter/ directory.
 *
 */

include_once "../../../wp-load.php";
include_once "../../../wp-admin/includes/file.php";
require_once "hugo-export.php";

$tmpFolder = $argv[1];

$je = new Hugo_Export();

if (isset($tmpFolder)) {
    if ('null' !== strtolower($tmpFolder) && is_dir($tmpFolder)) {
        echo "[INFO] Start to export data to configured folder $tmpFolder";
        $je->setTempDir($tmpFolder);
    } else {
        echo "[WARN] Passed TEMP folder $tmpFolder is not a valid folder. Remove the argument or create it as a folder before contiune";
        exit(1);
    }
    
} else {
    echo "[INFO] tmp folder not found, use default. You could invoke php hugo-export-cli.php with an extra argument as the temporary folder path if needful.";
}

$je->export();
```

And updated README.md with:

If you want to offer a folder (say a mount point to a huge drive) other than using `/tmp` in OS, pass it as the first argument to the script:

    php hugo-export-cli.php /YOUR_PATH_TO_TMP_FOLDER/

**Comment by lanshunfang** [comment]
Pull request created.

**Comment by SchumacherFM** [comment]
Merged! Thank you!

**Comment by lanshunfang** [comment]
My pleasure. Thank you for creating this fantastic plugin.
