### ISSUE TITLE
Should offer flag to toggle off zipping

### ISSUE THREAD

**Issue by lanshunfang** [SchumacherFM/wordpress-to-hugo-exporter#78]
## Requirement
I have a WordPress website with 10G+ size. I would like to publish the website to Github Pages. So here are the steps I've been doing:

- Generate Markdown via wordpress-to-hugo-exporter `cli`
- Deploy
- Remove all big files more than 2M
- Move the generated files into local git repo
- git add, commit and push

In the step of `Generating Markdown`, I don't need to create a hugo-export zip file (time & energy consuming).

## Proposal

*Usage*
```php
php hugo-export-cli.php ~/hugo/tmp/ --disable-zip --static-folder-name=hugo-export-tmp
```

*API*
- Add `disableZipping` method to `Hugo_Export` class
  - Bypass `Hugo_Export#zip()`, `Hugo_Export#send()` and `Hugo_Export#cleanup()` in `Hugo_Export#export()` if `Hugo_Export#disableZipping()` is called
  - Set `Hugo_Export#dir` to the passed in `--static-folder-name` (defaulted with `hugo-export-tmp`) so that automation pipeline could be easier; cleanup the folder if any previous copy exists before exporting.
- in `hugo-export-cli.php`, call `Hugo_Export#disableZipping()` if `--disable-zip` is set from php cli

**Comment by SchumacherFM** [comment]
This sounds great and if it does not break backwards compatibility, then go for it from my side!

**Comment by lanshunfang** [comment]
Sure. Let me do it soon.

BTW, I have some other enhancements to go, say parallel processing, audio / image optimization, only proceed changes (incremental changes on posts / uploads). I will only have them in my git repo and will create PR if tested & ran well.

**Comment by SchumacherFM** [comment]
closing due to age. reopen if desired.
