### ISSUE TITLE
Fatal error: Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by michaelsync** [SchumacherFM/wordpress-to-hugo-exporter#8]
Hello,

I am hosting my blog on Dreamhost and now, am planning to migrate to hugo. When I tried to export using "wordpress-to-hugo-exporter" plugin then I got the error below.

Fatal error: Maximum execution time of 30 seconds exceeded in /home/mysite/wp-admin/includes/class-wp-filesystem-direct.php on line 231

I downloaded the "wordpress-to-hugo-exporter" master as zip file and uploaded it from wordpress admin dashboard. I am not sure how to edit "php.ini" since I am on a shared host. 

Any idea how to fix it? Thanks in advance.

**Comment by SchumacherFM** [comment]
Please have either a look at http://php.net/manual/en/function.set-time-limit.php `set_time_limit(0)` (add this to your AFAIK index.php for a specific request ) or if you have SSH access then use the command line.

**Comment by michaelsync** [comment]
Thanks! I will try. But I think Dreamhost has a program that can detect and kill the process that uses high resource to be fair to other shared hosting users.

**Comment by SchumacherFM** [comment]
You can also simple dump the MySQL database into one file and import that data into your local region.

**Comment by michaelsync** [comment]
I tried adding set_time_out in index.php at the root web directory but didn't work. I downloaded the database.. I am just looking for a simple plugn that I can just upload and export to hugo. but seems like no chose but to install php and mysql stuffs on my machine then..

**Comment by SchumacherFM** [comment]
Seems like your dreamhost has turned into a nightmare host ;-)

If you have these timeouts the best way really is to download the whole database and let it run on your local development machine. There are many tutorials on the web on how to do it.

**Comment by michaelsync** [comment]
Hi SchumacherFM, 

I just like to confirm one thing first. 

I got that timeout error as soon as I click on "Export to Hugo" from Tool menu in wordpress admin dashboard. Is it expected? Should I see some UI or something first before I do the actual exporting? 

According to this Dreamhost link http://wiki.dreamhost.com/PHP.ini, it allows us to change the php.ini. What do I need to change there? max-execution-time=10000?  I am sorry if it's a stupid question. I am not familiar with php.
