### ISSUE TITLE
Embedded video parameters break Hugo's youtube/vimeo macros

### ISSUE THREAD

**Issue by stamkivi** [SchumacherFM/wordpress-to-hugo-exporter#82]
In my WordPress posts I occasionally have embedded Youtube / Vimeo videos (by pasting the embed codes from their respective web sites). The Hugo exporter plugin translates them appropriately to Hugo shortcodes in Markdown.

The issue is, that the shortcodes also pick up some parameters from original video URLs:
`{{< youtube PoUJvAQg7KI?rel=0 >}}  

{{< vimeo 51263340?byline=0&portrait=0&color=c9ff23 >}}  

{{< vimeo 47000322?title=0&byline=0&autoplay=0 >}}  
`

This results in:
`Error: Error building site: "<path to file>.md:407:24": unrecognized character in shortcode action: U+003F '?'. Note: Parameters with non-alphanumeric args must be quoted.`

Proposal is to either strip all URL parameters (from "?" symbol and forward), and pass only the video ID to shortcode. Or, potentially, pass the parameter in quotes (but I'm not sure if it would break the Hugo shortcode rendering into the video player?)

**Comment by SchumacherFM** [comment]
hi, thanks for the report. You can of course send me a pull request with your proposed change to strip all chars after the questions mark. I'm happy to merge it.
On the other hand: most users of this plugin convert their pages one and fix the errors manually ...

**Comment by stamkivi** [comment]
Yeah, I did a quick manual search-and-replace for my particular import, just figured I'd capture the issue for the future. So, not painful enough, as you noted too. :)

I guess the fix would go here -- maybe I'll return to this one day to learn some string manipulation tricks in PHP... :)
https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/af585baf1d107e56a9fd87578bbd21749eb527f8/includes/markdownify/Converter.php#L905

Thanks for providing this tool in any case! Worked as a charm for 99% of my ancient blog content.

**Comment by SchumacherFM** [comment]
We've updated the markdownify library .... maybe you can retry with version 2.0

**Comment by SchumacherFM** [comment]
seems like it has been solved, so closing. I can reopen on request.
