### ISSUE TITLE
Version number is wrong

### ISSUE THREAD

**Issue by RyanTG** [SchumacherFM/wordpress-to-hugo-exporter#85]
https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/9ab47d5eeb5cfdbdbb36647dbb52a902c106d2ed/hugo-export.php#L6

Shouldn't that be 2.0, and not 1.3? 

Just noticed that while I was on the wordpress plugins page.

**Comment by SchumacherFM** [comment]
fixed
