### ISSUE TITLE
blockquote not converted to markdown

### ISSUE THREAD

**Issue by thenktor** [SchumacherFM/wordpress-to-hugo-exporter#86]
Hi,

in my exported mardown file I have the following, which was not converted to markdown:
```
<blockquote class="wp-block-quote">
  You&#8217;ll take my life but I&#8217;ll take yours too You&#8217;ll fire your musket but I&#8217;ll run you through So when you&#8217;re waiting for the next attack You&#8217;d better stand there&#8217;s no turning back. <cite>Iron Maiden &#8211; The Trooper</cite>
</blockquote>
```

**Comment by SchumacherFM** [comment]
Hey, that might be possible that special HTML tags with its attributes are not getting converted.
Please do a "search and replace" action to easily replace the `<blockquote class="wp-block-quote">` and `</blockquote>`

**Comment by SchumacherFM** [comment]
closing this due to age. please reopen if the problem still exists.
