### ISSUE TITLE
How can I export while my wordpress is deployed on heroku?

### ISSUE THREAD

**Issue by johnsyin** [SchumacherFM/wordpress-to-hugo-exporter#88]
Hi, thanks for the awesome plugin.

I failed to export and I get error from heroku when I clicked export (it loaded for a while). It might be due to the fact that heroku uses an ephemeral filesystem. 

Anyone with similar experience here?

**Comment by SchumacherFM** [comment]
closing this due to age. please reopen if the problem still exists.
