### ISSUE TITLE
<code> tag conversion issue

### ISSUE THREAD

**Issue by michaelsync** [SchumacherFM/wordpress-to-hugo-exporter#9]
The html codes such as &lt;p&gt; and &lt;br/&gt; generated probably by wordpress should be removed from the text inside &lt;code&gt; tag. 

For example:  I have this in my wordpress blog. 

&lt;code&gt;
    int count = 1;
    Console.WriteLine(count);
&lt;/code&gt;

That code has been converted as below. 

\`
\<p\>int count = 1; \<br/\>    Console.WriteLine(count);\</p\>
\`

Is it an known issue? How do I fix it?

**Comment by SchumacherFM** [comment]
Sorry no idea.
