### ISSUE TITLE
Remove formatting while exporting.

### ISSUE THREAD

**Issue by end2endzone** [SchumacherFM/wordpress-to-hugo-exporter#90]
Hi. I used the plugin to export [my wordpress site](https://www.end2endzone.com/) hosted on [hostgator.com](https://www.hostgator.com/).

To my surprise, it seems that my posts, now in markdown format, are still having some formatting. I wish to get all formatting removed. Is there a way to export to hugo and get "plain markdown" without any formatting. At the time, I was preferring to use wordpress visual editor to set my desired formatting. I think that exporting to hugo would be a nice opportunity to start over and set all my formatting with css instead of having all my formatting in my post "raw data".

For examples:
* My level 1 headers `<h1>Introduction</h1>` are converted to `# <span id="Introduction">Introduction</span>`. I was expecting to only get `# Introduction`. 
* My markdown paragraphs are also wrapped in `<p style="text-align: justify;">text</p>`. This is certainly because my posts are stored as `<p style="text-align: justify;">text</p>` in the code editor.
* Markdown hyperlinks are exported as html. For example, I get `<a class="download-link" title="Version 1.2.219" href="http://www.end2endzone.com/download/2109/" rel="nofollow">Fade a LED example.ino</a>` instead of the expected `[Fade a LED example.ino](http://www.end2endzone.com/download/2109/)`.
* My lists are exported as html with sequences of `<li style="text-align: justify;">State #1 &#8211; IDLE (1000 ms)</li>` instead of plain markdown with `* State #1 &#8211; IDLE (1000 ms)`.

Can anyone give my hints on how to use this plugin to export to plain markdown ?

Note: I use [Mark Text](https://marktext.app/) as a visual markdown editor. The exported markdown is rendered properly but the editor gets easily confused and does not work.

**Comment by end2endzone** [comment]
I am also open to other suggestion such as a tool that could remove the formatting within the exported markdown (after using this plugin). Unfortunately, I don't know tool that could do this.

**Comment by end2endzone** [comment]
I looked at the code and tried to understand where I could help. Unfortunately, php is not my cup of tea. For example, I know I should be calling [setLinkPosition()](https://github.com/SchumacherFM/wordpress-to-hugo-exporter/blob/master/includes/markdownify/Converter.php#L289) but I think the code in markdonify (function [__construct()]() is hardcoded to use _reference-style links_ instead of _inline links_.

I ended up coding my own application that can filter the output of _wordpress-to-hugo-exporter_.
The code can be found at [end2endzone/end2endzone-wp-hugo-migration](https://github.com/end2endzone/end2endzone-wp-hugo-migration).


It contains two applications:

**_filterimagesizes_**

Search in a `wp-content` directory for image sizes and delete them leaving only the master image.

Features:

- Replaces in posts any reference of a sub image size by the highest resolution image.
- Delete images sub sizes from `wp-content` directory. The highest resolution image is not deleted.
 
  

## filterhtml

Replace html formatting in a markdown file by native markdown syntax.

Features:

- The following html tags are supported: `span`, `p`, `img`, `a`, `strong`, `i`, `em`, `code`, `ul`, `li`, `pre`, `div`, `table`.
- The function `filter_paragraph_with_custom_css()` supports paragraph with custom css classes which were specific for by blog. These paragraphs are converted and a shortcode matching the custom css class is added before and after the paragraph's content. Replace the list of custom classes by yours to get the same result.
- [Wordpress galleries](https://wordpress.org/support/article/the-wordpress-gallery/) are properly identified and converted to a markdown table.
- Html tables which are missing an header row (or if the header row cannot be identified) have an additional empty row added at the beginning as the header.
- Most known html entities are replaced by their corresponding utf-8 character.
- Whitespace is removed as much as possible.
- [Reference-style links](https://www.markdownguide.org/basic-syntax/#reference-style-links) are replaced by [inline links](https://www.markdownguide.org/basic-syntax/#formatting-links).
- Featured_image element in front matter is replaced by image.src format.

**Comment by end2endzone** [comment]
My issue has been resolved. You can close the issue or leave it open if you think someone else can contribute to the code and implement a fix that is more appropriate than what I did.

**Comment by SchumacherFM** [comment]
closing this due to age. please reopen if the problem still exists.
