### ISSUE TITLE
LICENSE or COPYING file missing from root directory

### ISSUE THREAD

**Issue by TechnologyClassroom** [SchumacherFM/wordpress-to-hugo-exporter#91]
I see this project is under GPL-3.0-or-later. Adding a LICENSE or COPYING file to the root directory would make this very obvious for people new to the project and show up in the About header on the first page view of the project.

Would you like me to make a PR to create the file?

**Comment by SchumacherFM** [comment]
Dear Michael, thank you very much for that hint. I'm highly thankful if you can add a PR with this change!
