### ISSUE TITLE
CLI command returning Error establishing a database connection message

### ISSUE THREAD

**Issue by AdamChlan** [SchumacherFM/wordpress-to-hugo-exporter#93]
I have successfully used this plugin many times, mostly from the WP Admin, but also using the CLI. Triggering the export from the WP Admin still works for me, but now when I try to run from the CLI, it says it cannot connect to the database, but everything is configure correctly. Curious if anyone else has seen this issue before. I'm guessing something has changed on my local that is impacting this. I have tried various versions of PHP 7, with no luck.

**Comment by SchumacherFM** [comment]
The failing of the connection to the database is independent of the PHP version ;-)
It seems more like that your CLI does not load the configuration to access MySQL and even does not initialize the connection itself via e.g. `mysql_connect`. Try to include a wordpress file/class which is responsible to set up a DB connection.
Review other CLI files how they are doing it.

**Comment by SchumacherFM** [comment]
closing this due to age. please reopen if the problem still exists.
