### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by nicfab** [SchumacherFM/wordpress-to-hugo-exporter#94]
Hi!
I correctly installed the plugin on two different WordPress sites, but I clicked on "Export to Hugo", and after some seconds, I received the error in the subject "504 Gateway Time-out".
I tried several times but the issue is always the same.
Any solution?

**Comment by SchumacherFM** [comment]
Hey, thanks for reporting. Maybe the script time execution limit is too low to generate the export files. So your hoster will kill the php process before it finishes. maybe you can change this somehow. 
also the best way to run this exporter is via command line.

**Comment by nicfab** [comment]
Thank you. 
Can you tell what command should I run via command line (I suppose on the server and not locally)?

**Comment by SchumacherFM** [comment]
Yes on the server https://github.com/SchumacherFM/wordpress-to-hugo-exporter#command-line-usage

**Comment by nicfab** [comment]
Thank you for your quick reply
