### ISSUE TITLE
hugo won't show exported posts in my homepage

### ISSUE THREAD

**Issue by gitarkatili** [SchumacherFM/wordpress-to-hugo-exporter#98]
hello, i recently exported my wordpress data and copied the downloaded .md files into my hugo posts folder, and ran the local server. it did not show any exported posts but only my first post, which i generated from cli. i can explore my exported tags, dates etc. only problem is i can't navigate to any exported content from my main page.
i also generate a static page and ran it, problem still occurs. thanks.

**Comment by SchumacherFM** [comment]
hey, sorry, please post your question into the gohugo forum https://discourse.gohugo.io/
