### ISSUE TITLE
Use Pandoc instead of Markdownify

### ISSUE THREAD

**Issue by evert-mouw** [SchumacherFM/wordpress-to-hugo-exporter#99]
Markdownify is a bit old and limited; in my experience, Pandoc does a much better job preserving pictures and captions.

You need to have pandoc installed. A pandoc wrapper is available: https://github.com/ryakad/pandoc-php

It's quite easy to implement this. For `hugo-export.php`, do:

```
    public $required_classes = array(
        'spyc' => '%pwd%/includes/spyc.php',
        'Pandoc\Pandoc' => '%pwd%/includes/pandoc-php/Pandoc.php',
    );
```

and change this function

```
    function convert_content($post)
    {
        $content = apply_filters('the_content', $post->post_content);
        #$converter = new Markdownify\ConverterExtra;
        #$markdown = $converter->parseString($content);
        $pandoc = new Pandoc\Pandoc;
        $markdown = $pandoc->convert($content, "html", "markdown");
```
The difference is shown below.

Markdownify:

```
<div class="wp-block-image">
  <figure class="aligncenter size-large"><img loading="lazy" width="800" height="600" src="https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-800x600.jpg" alt="scan uit boek" class="wp-image-5784" srcset="https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-800x600.jpg 800w, https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-300x225.jpg 300w, https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-768x576.jpg 768w, https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-1536x1152.jpg 1536w, https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-2048x1536.jpg 2048w" sizes="(max-width: 800px) 100vw, 800px" /><figcaption>Waarheid en wil bij Augustinus (Belijdenissen)</figcaption></figure>
</div>
```

Pandoc:

```
::: wp-block-image
![Waarheid en wil bij Augustinus
(Belijdenissen)](https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-800x600.jpg){.wp-image-5784
loading="lazy" width="800" height="600"
srcset="https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-800x600.jpg 800w, https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-300x225.jpg 300w, https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-768x576.jpg 768w, https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-1536x1152.jpg 1536w, https://www.furorteutonicus.eu/wp-content/uploads/2022/08/Waarheid-en-wil-bij-Augustinus-Belijdenissen-2048x1536.jpg 2048w"
sizes="(max-width: 800px) 100vw, 800px"}
:::
```

Pandoc still produces a mess, but it's markdown at least. It looks better using Hugo, anyway. YMMV, but maybe this can benefit some folks.

**Comment by SchumacherFM** [comment]
hey,

thanks for the suggestion .... but Markdownify is nativ php code while pandoc requires an external package to be installed on a server. Not everybody has the permission to install additional software.

What you can do for this project: Create a pull request where the package consumer can choose between pandoc and Markdownify. Default option is always Markdownify.
Add a code line when pandoc is not installed that it returns a human readable error to install pandoc.

How about that?

**Comment by evert-mouw** [comment]
I'm already done exporting and now busy editing all posts of my blog. Wordpress makes quite a mess -- also pandoc didn't solve all that.... Anyway. Not much time to play with code ATM. And agreed, pandoc is external and an additional dependency = bad. Maybe we should not pursue this. If someone really needs pandoc, then it's easy to edit the php sources with the examples above. After hand editing loads of files for the last few hours, I'm a bit less enthousiastic than when I opended this issue...
